config/routes.rb
Mobplug::Application.routes.draw do
  
  resource :contact, :only => [:show, :create]
  resources :roles, :except => [:show]
  resources :categories
  resources :projects
  resources :sessions, :only => [:create]
  
  match "login" => "sessions#new"
  match "logout" => "sessions#destroy"
  match "home" => "home#index"
  match "about" => "about#index", :as => :about
  
  root :to => "home#index"
  
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :project
  has_attached_file :image, :styles => { :thumb=> "160x120#", :small  => "260x180#" },
    :storage => Rails.env.production? ? :s3 : :filesystem,
    :bucket => 'luizbranco_imgs',
    :s3_credentials => {
      :access_key_id => ENV['S3_KEY'],
      :secret_access_key => ENV['S3_SECRET']
  }

  default_scope order('id ASC')

end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, :use => :slugged
  has_many :tags
  has_many :projects, :through => :tags

  validates :name, :presence => true

  default_scope order(:name)
end

app/models/contact.rb
class Contact
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  
  attr_accessor :name, :email, :subject, :message
  
  validates :name, :presence => true
  validates :email, :presence => true, :format => { :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i }
  validates :subject, :presence => true
  validates :message, :presence => true, :length => { :maximum => 500 }
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
  
  def persisted?
    false
  end
  
end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, :use => :slugged
  has_many :tags, :dependent => :destroy
  has_many :categories, :through => :tags
  has_many :rolerships, :dependent => :destroy
  has_many :roles, :through => :rolerships
  has_many :assets, :dependent => :destroy
  accepts_nested_attributes_for :assets, :allow_destroy => true

  validates :name, :presence => true
  validates :description, :presence => true
  validates :launch, :presence => true
  validates_associated :assets

  default_scope order('launch DESC')

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :rolerships
  has_many :projects, :through => :rolerships

  validates :name, :presence => true

  default_scope order(:name)
end

app/models/rolership.rb
class Rolership < ActiveRecord::Base
  belongs_to :project
  belongs_to :role
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :category
  belongs_to :project
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @title = 'About Luiz Branco'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :create_body_identifiers
  
  helper_method :admin?
  
  def show_errors(target)
    if target.errors.any?
      flash[:error] ||= []
      target.errors.full_messages.each do |msg|
        flash[:error] << msg
      end
    else
      flash[:error] = 'An error has occured!'
    end
  end
  
  def create_body_identifiers
    @body_class = params[:controller]
    @body_id = params[:action]
  end
  
  def authorize
    unless admin?
      flash[:error] = "Not here, Cowboy!"
      redirect_to root_path
      false
    end
  end
  
  def admin?
    session[:password]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authorize, :except => [:index, :show]

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @projects = @category.projects
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category])
    if @category.save
      redirect_to category_path(@category), :notice => 'A new category was created!'
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(params[:category])
      redirect_to category_path(@category), :notice => 'Your category was updated!'
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      redirect_to categories_path, :notice => 'Your category was deleted!'
    end
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def show
    @title = 'Get in touch!'
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    if @contact.valid? && ContactMailer.send_email(@contact).deliver
      redirect_to root_path, :notice => "Your message has been sent!"
    else
      render :show
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @projects = Project.limit(4)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authorize, :except => [:index, :show]
  before_filter :load_resources, :only => [:new, :create, :edit, :update]

  def index
    @categories = Category.all
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
    @categories = @project.categories
    @roles = @project.roles
    @assets = @project.assets
  end

  def new
    @project = Project.new
    4.times {@project.assets.build}
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      redirect_to project_path(@project), :notice => 'A new project was created!'
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
    4.times {@project.assets.build}
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      redirect_to project_path(@project), :notice => 'Your project was updated!'
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      redirect_to projects_path, :notice => 'Your project was deleted!'
    end
  end

  private

  def load_resources
    @roles = Role.all
    @categories = Category.all
  end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :authorize

  def index
    @roles = Role.all
  end

  def new
    @role = Role.new
  end

  def create
    @role = Role.new(params[:role])
    if @role.save
      redirect_to roles_path, :notice => 'A new role was created!'
    else
      render :new
    end
  end

  def edit
    @role = Role.find(params[:id])
  end

  def update
    @role = Role.find(params[:id])
    if @role.update_attributes(params[:role])
      redirect_to roles_path, :notice => 'Your role was updated!'
    else
      render :edit
    end
  end

  def destroy
    @role = Role.find(params[:id])
    if @role.destroy
      redirect_to roles_path, :notice => 'Your role was deleted!'
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
	  ENV['PASSWORD'] ||= 'foobar'
	  if params[:password] == ENV['PASSWORD']
	    session[:password] = params[:password]
		  redirect_to root_path, :notice => 'Welcome Back!'
	  else
		  redirect_to login_path, :alert => 'Invalid Password!'
	  end
	end

	def destroy
		reset_session
		redirect_to root_path, :notice => 'See you later!'
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def is_controller_active?(controller)
    if controller.include?(params[:controller])
      "active"
    end
  end

  def title
    base_title = "luizbranco"
    if @title.nil?
      base_title
    else
      "#{base_title} :: #{@title}"
    end
  end

  def description
    unless @description.nil?
      @description
    end
  end

  def error_messages_for(object)
    render :partial => 'shared/error_messages', :locals => {:object => object}
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper

  def list_categories(project)
    unless project.categories.empty?
      list = []
      project.categories.each do |category|
        list << normalize_name(category)
      end
      list.join(" ")
    end
  end

  def normalize_name(category)
    category = category.name.downcase.gsub(" ","_")
  end

end

app/views/about/index.html.haml
:markdown
  ## About me
  I excel at collaborative product design for early-stage startups who seek rapid and responsive design strategy, as well as with large businesses seeking disruptive change and innovation.

  As a product strategist, I help teams to integrate the "build-measure-learn" cycles for continuous validated learning. I have great experience working on fast paced environment using Lean techniques focused on small batches and incremental releases.

  My core product design skills include user research, user roles and scenarios creation, acceptance tests, product visioning, sketching, wireframes, prototypes and guerrilla usability techniques.

%h2 Where to find me
= link_to 'http://github.com/luizbranco', :class => 'btn' do
  %i.icon-folder-open
  Github
= link_to 'http://linkedin.com/in/luizbranco', :class => 'btn' do
  %i.icon-user
  LinkedIn

app/views/categories/_form.html.haml
= error_messages_for(category)
= form_for category, :html => {:class => "form-inline"} do |f|
  %div.control-group
    =f.label :name
    =f.text_field :name, :autofocus => true
    =f.submit :class => 'btn btn-success'

app/views/categories/edit.html.haml
%h2 Edit Category
= render 'form', :category => @category

app/views/categories/index.html.haml
%h2 Categories
- if admin?
  = link_to new_category_path, :class => 'btn btn-success' do
    %i.icon-plus.icon-white
    New Category
%hr.soften
%ul.unstyled
  - @categories.each do |category|
    %li= link_to category.name, category_path(category)

app/views/categories/new.html.haml
%h2 New Category
= render 'form', :category => @category

app/views/categories/show.html.haml
%h2= @category.name
- if admin?
  = link_to edit_category_path(@category), :class => 'btn' do
    %i.icon-pencil
    Edit
  = link_to category_path(@category), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-danger' do
    %i.icon-trash.icon-white
    Delete
  %hr.soften
%ul.thumbnails.span8
  = render @projects

app/views/contacts/index.html.haml
%h2 Get in touch
=form_for @contact do |f|
  =f.label :name, 'Name'
  =f.text_field :name
  =f.label :email, 'Email'
  =f.email_field :email
  =f.label :subject, 'Subject'
  =f.text_field :subject
  =f.label :message, 'Message'
  =f.text_area :message
  =f.submit 'Send Email'
  

app/views/contacts/show.html.haml
%h2 Contact
.row
  = error_messages_for(@contact)
  =form_for @contact, :url => contact_path, :html => { :class => "form-horizontal"}  do |f|
    %div.control-group
      =f.label :name, :class => 'control-label'
      %div.controls
        =f.text_field :name, :class => 'input-xlarge', :autofocus => true
    %div.control-group
      =f.label :email, :class => 'control-label'
      %div.controls
        =f.email_field :email, :class => 'input-xlarge'
    %div.control-group
      =f.label :subject, :class => 'control-label'
      %div.controls
        =f.text_field :subject, :class => 'input-xlarge'
    %div.control-group
      =f.label :message, :class => 'control-label'
      %div.controls
        =f.text_area :message, :class => 'input-xlarge', :rows => '6'
    %div.form-actions
      =f.submit 'Send', :class => 'btn btn-primary'

app/views/home/index.html.haml
- @title = "Product Manager and Ruby Developer"
.row.introduction
  %div.well
    :markdown
      ##I'm a **Product Manager** and **Ruby Developer**
      ##with a passion for **powerfully simple products**
%hr.soften
%h2 Recent Projects
.row
  %ul.thumbnails
    - @projects.each do |project|
      %li.span3
        = link_to project_path(project), :class => 'thumbnail' do
          - if project.assets.any?
            = image_tag project.assets.first.image.url(:small), :title => project.name
          .caption
            %h5= project.name
%hr.soften
%div.center
  =link_to projects_path, :class => "btn btn-primary" do
    %i.icon-th-list.icon-white
    View all Projects

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= title
    %meta{:name => 'description', :content => "#{@description}"}
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = render :partial => 'shared/ga'
  %body
    %div.container
      %header.row
        %div.span4
          %h1= link_to 'luizbranco', root_path
        = render :partial => 'shared/main_nav'
      = render :partial => 'shared/flash_messages'
      = yield
    %footer
      %div#scenario
        =image_tag(asset_path("me.gif"), :title => "It's me, Luiz!")
      %div#ground  

app/views/projects/_form.html.haml
.row
  = error_messages_for(project)
  = form_for project, :html => {:class => "form-horizontal", :multipart => true } do |f|
    %div.control-group
      = f.label :name, :class => 'control-label'
      %div.controls
        = f.text_field :name, :class => 'input-xlarge', :autofocus => true
    %div.control-group
      = f.label :description, :class => 'control-label'
      %div.controls
        = f.text_area :description, :class => 'input-xlarge', :rows => '6'
    %div.control-group
      = f.label :url, :class => 'control-label'
      %div.controls
        = f.text_field :url, :class => 'input-xlarge', :placeholder => 'http://'
    .control-group
      = f.label :launch, 'Launch Date', :class => 'control-label'
      .controls
        =f.date_select(:launch, {:discard_day => true, :start_year => Time.now.year-2, :end_year => Time.now.year}, {:class => 'span2'})
    %fieldset
      %legend Images
      = f.fields_for :assets do |asset|
        - if asset.object.new_record?
          %div.controls
            = asset.file_field :image
        - else
          %div.controls
            = link_to( image_tag(asset.object.image.url(:thumb)), asset.object.image.url(:original) )
          %div.controls
            = asset.label :_destroy, :class => 'checkbox' do
              Delete Image
              = asset.check_box :_destroy
    %field_set
      %legend Categories
      - categories.each do |category|
        %div.controls
          = label_tag "category_#{category.id}", :class => 'checkbox' do
            = category.name
            = check_box_tag "category_#{category.id}", category.id, project.categories.include?(category), :name => 'project[category_ids][]'
    %field_set
      %legend Roles
      - roles.each do |role|
        %div.controls
          = label_tag "role_#{role.id}", :class => 'checkbox' do
            = role.name
            = check_box_tag "role_#{role.id}", role.id, project.roles.include?(role), :name => 'project[role_ids][]'
    %div.form-actions
      = f.submit :class => 'btn btn-success'

app/views/projects/_project.html.haml
%li{"data-categories" => list_categories(project), :class => 'span8'}
  - if project.assets.any?
    = link_to project_path(project), :class => 'thumbnail span2' do
      = image_tag(project.assets.first.image.url(:thumb))
  .span5
    %h4= link_to project.name, project_path(project)
    %p= project.description.truncate(55)
    - unless project.categories.empty?
      .project_categories
        %h4 Categories:
        %ul.project_categories
          - project.categories.each do |category|
            %li= category.name
    - unless project.roles.empty?
      .project_roles
        %h4 Roles:
        %ul.project_roles
          - project.roles.each do |role|
            %li= role.name

app/views/projects/edit.html.haml
%h2 Edit Project
= render 'form', :project => @project, :categories => @categories, :roles => @roles

app/views/projects/index.html.haml
- @title = "All Luiz Branco's Projects"
%h2 Projects
- if admin?
  = link_to new_project_path, :class => 'btn btn-success' do
    %i.icon-plus.icon-white
    New Project
  %hr.soften
.row
  %ul.thumbnails.span8#project_list
    = render @projects
  .span4
    %h3 Categories
    %ul.nav.nav-pills.nav-stacked#category_menu
      %li{'data-category' => 'all', :class => 'active'}= link_to 'All Categories', categories_path
      - @categories.each do |category|
        %li{'data-category' => normalize_name(category)}= link_to category.name, category_path(category)

app/views/projects/new.html.haml
%h2 New Project
= render 'form', :project => @project, :categories => @categories, :roles => @roles

app/views/projects/show.html.haml
- @title = @project.name
- @description = @project.description
%h2= @project.name
- if admin?
  = link_to edit_project_path(@project), :class => 'btn' do
    %i.icon-pencil
    Edit
  = link_to project_path(@project), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-danger' do
    %i.icon-trash.icon-white
    Delete
  %hr.soften
- if @project.assets.any?
  %ul.thumbnails.span12
    - @assets.each do |asset|
      %li.thumbnail.thumbnail-white.span3
        = link_to asset.image.url(:original), :class => 'full_project_img' do
          =image_tag(asset.image.url(:small))
= simple_format(@project.description)
- if @project.launch
  .project_launch
    %h4 Launch:
    = @project.launch.strftime('%b / %Y')
- if @project.categories.any?
  .project_categories
    %h4 Categories:
    %ul.unstyled
      - @categories.each do |category|
        %li= category.name
- if @project.roles.any?
  .project_categories
    %h4 Roles:
    %ul.unstyled
      - @roles.each do |role|
        %li= role.name
%hr.soften
- unless @project.url.empty?
  = link_to @project.url, :class => 'btn btn-primary' do
    Visit Project
    %i.icon-share-alt.icon-white

app/views/roles/_form.html.haml
= error_messages_for(role)
= form_for role, :html => {:class => "form-inline"} do |f|
  %div.control-group
    =f.label :name
    =f.text_field :name, :autofocus => true
    =f.submit :class => 'btn btn-success'

app/views/roles/edit.html.haml
%h2 Edit Role
= render 'form', :role => @role

app/views/roles/index.html.haml
%h2 Roles
= link_to new_role_path, :class => 'btn btn-success' do
  %i.icon-plus.icon-white
  New Role
%hr.soften
%ul.unstyled
  - @roles.each do |role|
    %li
      = role.name
      = link_to edit_role_path(role), :class => 'btn' do
        %i.icon-pencil
        Edit
      = link_to role_path(role), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-danger' do
        %i.icon-trash.icon-white
        Delete

app/views/roles/new.html.haml
%h2 New Role
= render 'form', :role => @role

app/views/shared/_error_messages.html.haml
- if object && object.errors.any?
  .alert.alert-error.alert-block
    %h4.alert-heading The following errors prevented the requested action
    %ul.unstyled
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_flash_messages.html.haml
- flash.each do |name, msg|
  .alert
    - if msg.is_a?(String)
      %div= msg
    - else
      - msg.each do |m|
        %div= m

app/views/shared/_ga.html.haml
:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-4624241-2']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

app/views/shared/_main_nav.html.haml
%div.span4
  %ul.nav.nav-pills
    %li{:class => "#{is_controller_active?('home')}"}
      =link_to 'home', root_path
    %li{:class => "#{is_controller_active?(['projects', 'categories'])}"}
      =link_to 'projects', projects_path
    %li{:class => "#{is_controller_active?('about')}"}
      =link_to 'about', about_path
    %li{:class => "#{is_controller_active?('contacts')}"}
      =link_to 'contact', contact_path